### ISSUE TITLE
Palatino Font Package error

### ISSUE THREAD

**Issue by mmccorml** [nmfs-opensci/quarto_titlepages#30]
### Background

Used Quarto in RStudio to render the example.qmd quarto document after installing tinytext but do not have MikText or MacTeX installed. 

### Problem Description

an error pops up that says RStudio can not find the Palatino Font package. 

### Replication Steps

opened eample.qmd and hit render

### Possible Solutions

Went to an openscapes coworking session and someone with MikText with the qualitype package ran the same code and it worked for her. Our next step will be to ask IT to download MikTex or Tex Live. Having no experience with LaTeX at all, is one of those programs better to download then the other? 

Thanks for your help!

**Comment by eeholmes** [comment]
I just fixed this this afternoon. The font is called "Palatino Linotype" on Windows while it is called "Palatino" on Mac. I just cut out the Palatino font reference altogether.

To update to the newest version of quarto_titlepages run from a terminal in your project. So if your RStudio project is at `C:/Users/MM/Document/MyProject` you want to open a terminal window and cd to that directory.
```
quarto install extension nmfs-opensci/quarto_titlepages
```

**Comment by eeholmes** [comment]
@mmccorml Regarding what TeX to install, **you do not want MikTeX or TeX Live!** For making PDFs with R Markdown or Quarto (in RStudio) you want tinytex. You should be able to install if right from RStudio, however before you do that, you may have tinytex already since Quarto may bundle it.  Update the quarto_titlepages and try to render again.

If it says it doesn't have TeX, then run the following from the R command line:
```
install.packages('tinytex')
tinytex::install_tinytex()
```

**Comment by mmccorml** [comment]
Okay great, thank you for your help!
