### ISSUE TITLE
Can't run titlepages

### ISSUE THREAD

**Issue by mhollanders** [nmfs-opensci/quarto_titlepages#8]
### Prerequisites

* [ x] Put an X between the brackets on this line if you have done all of the following:
    * Followed all applicable steps in the debugging guide: <https://github.com/Openscapes/2021-noaa-nmfs/wiki/2-Issues-and-Project-Boards>
    * Checked the FAQs on the message board for common solutions
    * Checked that your issue isn't already filed.

### Description

I tried to run the thesis-static titlepage for a Quarto book I'm making, and it didn't work. So I just tried to run the article.qmd files in the thesis-static and also great-wave folders and neither of them produce the desired title pages.

### Steps to Reproduce

1.  open article.qmd and setwd() to the right folder
2. Render

**Expected behavior:**

The article.pdf to look like the article.pdf on the Github

**Actual behavior:**

Errors. No title page for thesis-static and "compilation failed- error
LaTeX Error: Environment abstract undefined." for great-wave.

**Reproduces how often:**

100%.

### Versions

atom --version and apm --version command not working on my machine. MacOS 12.4, R 4.2.0, RStudio 2022.7.1

**Comment by MHollanders** [comment]
Hey, thanks so much for the quick response! So it turns out it was the
Quarto version, I thought it got updated automatically with the new
RStudio. Anyway, it does knit and produce the title page, but it has caused
a range of other errors, including: some headers show up with "##", there's
a random header here and there, and equations are not rendered properly
(see screenshot for example). Any idea why that is?

**Comment by MHollanders** [comment]
Hey, so it turns out the problem was in-header.tex file. I don't think
those packages getting loaded played ball with the maths...

**Comment by eeholmes** [comment]
- [ ] Try again to replicate (couldn't on my Mac or RStudio Cloud)
- [ ] Add Quarto version dependency (not sure how)
